export const ANIMALS = {
    PUG: 'PUG',
    BUTTERFLY: 'BUTTERFLY',
    TURTLE: 'TURTLE',
    KITTEN: 'KITTEN',
    ORCA: 'ORCA',
    ELK: 'ELK',
    PENGUIN: 'PENGUIN',
    DUCKLING: 'DUCKLING',
    GORILLA: 'GORILLA',
    LION: 'LION',
    PANDA: 'PANDA',
    ELEPHANT: 'ELEPHANT',
    BEAR: 'BEAR',
    SHARK: 'SHARK',
    BLOBFISH: 'BLOBFISH',
    NAKEDMOLERAT: 'NAKEDMOLERAT',
}

export const ANIMAL_ORDER = [
    ANIMALS.PUG,
    ANIMALS.BUTTERFLY,
    ANIMALS.TURTLE,
    ANIMALS.KITTEN,
    ANIMALS.ORCA,
    ANIMALS.ELK,
    ANIMALS.PENGUIN,
    ANIMALS.DUCKLING,
    ANIMALS.GORILLA,
    ANIMALS.LION,
    ANIMALS.PANDA,
    ANIMALS.ELEPHANT,
    ANIMALS.BEAR,
    ANIMALS.SHARK,
    ANIMALS.BLOBFISH,
    ANIMALS.NAKEDMOLERAT
]

export const ANIMAL_TEXTURES = {
    [ANIMALS.PUG]: 'pugTile.png',
    [ANIMALS.BUTTERFLY]: 'butterflyTile.png',
    [ANIMALS.TURTLE]: 'turtleTile.png',
    [ANIMALS.KITTEN]: 'kittenTile.png',
    [ANIMALS.ORCA]: 'orcaTile.png',
    [ANIMALS.ELK]: 'elkTile.png',
    [ANIMALS.PENGUIN]: 'penguinTile.png',
    [ANIMALS.DUCKLING]: 'ducklingTile.png',
    [ANIMALS.GORILLA]: 'gorillaTile.png',
    [ANIMALS.LION]: 'lionTile.png',
    [ANIMALS.PANDA]: 'pandaTile.png',
    [ANIMALS.ELEPHANT]: 'elephantTile.png',
    [ANIMALS.BEAR]: 'bearTile.png',
    [ANIMALS.SHARK]: 'sharkTile.png',
    [ANIMALS.BLOBFISH]: 'blobfishTile.png',
    [ANIMALS.NAKEDMOLERAT]: 'nakedmoleratTile.png',
}
