export const ANIMALS = {
    PUG: 'PUG',
    BUTTERFLY: 'BUTTERFLY',
    TURTLE: 'TURTLE',
    KITTEN: 'KITTEN',
    ORCA: 'ORCA',
    ELK: 'ELK',
    PENGUIN: 'PENGUIN',
    DUCKLING: 'DUCKLING',
    GORILLA: 'GORILLA',
    LION: 'LION',
    PANDA: 'PANDA',
    ELEPHANT: 'ELEPHANT',
    BEAR: 'BEAR',
    SHARK: 'SHARK',
    BLOBFISH: 'BLOBFISH',
    NAKEDMOLERAT: 'NAKEDMOLERAT',
}

export const ANIMALS_ORDERED = [
    ANIMALS.PUG,
    ANIMALS.BUTTERFLY,
    ANIMALS.TURTLE,
    ANIMALS.KITTEN,
    ANIMALS.ORCA,
    ANIMALS.ELK,
    ANIMALS.PENGUIN,
    ANIMALS.DUCKLING,
    ANIMALS.GORILLA,
    ANIMALS.LION,
    ANIMALS.PANDA,
    ANIMALS.ELEPHANT,
    ANIMALS.BEAR,
    ANIMALS.SHARK,
    ANIMALS.BLOBFISH,
    ANIMALS.NAKEDMOLERAT
]

export const RARITIES = {
    COMMON: 'COMMON',
    UNCOMMON: 'UNCOMMON',
    RARE: 'RARE',
    SUPER_RARE: 'SUPER_RARE',
    EPIC: 'EPIC',
}

export const RARITIES_ORDERED = [
    RARITIES.COMMON,
    RARITIES.UNCOMMON,
    RARITIES.RARE,
    RARITIES.SUPER_RARE,
    RARITIES.EPIC,
]

export const ANIMAL_RARITIES = {
    [ANIMALS.PUG]: RARITIES.COMMON,
    [ANIMALS.BUTTERFLY]: RARITIES.COMMON,
    [ANIMALS.TURTLE]: RARITIES.COMMON,
    [ANIMALS.KITTEN]: RARITIES.COMMON,
    [ANIMALS.ORCA]: RARITIES.UNCOMMON,
    [ANIMALS.ELK]: RARITIES.UNCOMMON,
    [ANIMALS.PENGUIN]: RARITIES.UNCOMMON,
    [ANIMALS.DUCKLING]: RARITIES.UNCOMMON,
    [ANIMALS.GORILLA]: RARITIES.RARE,
    [ANIMALS.LION]: RARITIES.RARE,
    [ANIMALS.PANDA]: RARITIES.RARE,
    [ANIMALS.ELEPHANT]: RARITIES.RARE,
    [ANIMALS.BEAR]: RARITIES.SUPER_RARE,
    [ANIMALS.SHARK]: RARITIES.SUPER_RARE,
    [ANIMALS.BLOBFISH]: RARITIES.EPIC,
    [ANIMALS.NAKEDMOLERAT]: RARITIES.EPIC,
}
